version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway,sts,cognito-idp,cloudwatch,logs,iam,secretsmanager,sqs,sns
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.localstack:/var/lib/localstack'
    networks:
      - madmall-local

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - '8001:8001'
    depends_on:
      - localstack
    networks:
      - madmall-local

networks:
  madmall-local:
    driver: bridge

